---
title             : "Attraction Effect in Risky Choices"
shorttitle        : "Attractive Risk"
author: 
  - name          : "Yi-tsen Liao"
    affiliation   : "1"
    corresponding : yes    
    address       : "The Hong Kong University of Science and Technology, Hong Kong"
    email         : "yliaoav@connect.ust.hk"
affiliation:
  - id            : "1"
    institution   : "The Hong Kong University of Science and Technology"
note : |
  
  `r format(Sys.time(), "%e %B, %Y")`
authornote: |
  The author gratefully acknowledges Professors David Hagmann and Yang Lu for their invaluable mentorship and guidance. Thanks also to the HKUST Economics Department for financial support that made the experiment in this thesis possible. Special thanks to Professor Hagmann for the much-needed pep talks and for talking the author out of her seasonal imposter syndrome episodes throughout her undergraduate year
abstract: |
  
  This study investigates the attraction effect—a well-documented context-dependent preference reversal—in the domain of risky choices. While prior research has established the robustness of the attraction effect in consumer decisions, its role in decision-making under risk and uncertainty remains underexplored. This paper contributes to this literature by examining whether introducing an asymmetrically dominated decoy option can systematically shift preferences between lotteries. Using an incentivized within-subject experimental design (N = 603), we manipulate the similarity and dominance of decoy lotteries to test their influence on the selection of a focal risky or safe option. The focal and non-focal lotteries are identical in expected value but differ in their risk profiles, enabling us to isolate context effects from baseline risk preferences. Our findings suggest an asymmetric attraction effect: while decoys dominated by the risky option significantly increased its selection likelihood (by 5.6 percentage points, p < .001), decoys dominated by the safe option had no positive effect and even slightly decreased its attractiveness. This asymmetry in our experimental evidences suggest that the attraction effect on risky choices is better explained by attribute-based rather than value-based accounts, challenging prior results from perceptual and consumer choice studies. These results deepen our understanding of context-dependent preferences in risk settings and highlight the role of attribute salience in shaping economic decision-making under uncertainty.
keywords          : "Attraction effect, Risky choice, Context effects, Preference reversal"
wordcount         : "6,400"
floatsintext      : yes
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no
documentclass     : "apa7"
csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
fig-cap-location  : "top"
classoption       : "man"
header-includes:
   - \usepackage{setspace, appendix, placeins, booktabs, tikz, siunitx, tabularx}
   - \usetikzlibrary{positioning}
   - \usetikzlibrary{arrows.meta}
   - \raggedbottom
   - \usepackage{caption, pdflscape, colortbl}
   - \usepackage{float, titletoc}
   - \floatstyle{plaintop}
   - \restylefloat{figure}
# bibliography      : bibliography.bib
output: 
  papaja::apa6_pdf
  # papaja::apa6_word
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 72
---


```{r setup, include = FALSE}
library(magrittr)
library(ggplot2)
library(ggpubr)
library(modelsummary)
library(estimatr)
library(lme4)

knitr::opts_chunk$set(fig.width = 8, fig.height = 7)
knitr::opts_chunk$set(warning = FALSE)

study1 <- readRDS(here::here("data/study1.Rds"))
study1_complete <- readRDS(here::here("data/study1_complete.Rds"))
study1_change <- readRDS(here::here("data/study1_change.Rds"))

```


# Introduction

In risk_averse condition, introducing the decoy shifted people from choosing the safe lotteries to choosing the risky lotteries.

In risk_seeking condition, introducing the decoy shifted people from choosing the decoy to choosing the risky lotteries.

```{r}
# Frequency table

study1_complete %>%
  dplyr::group_by(condition, treatment, raw_choice)%>%
  dplyr::summarise(n = dplyr::n(), .groups = "drop")

study1 %>%
  dplyr::group_by(condition, treatment, raw_choice)%>%
  dplyr::summarise(n = dplyr::n(), .groups = "drop")
  
```



```{r}
# Main regression -- all conditions

modelsummary::modelsummary(list(`Focal Lottery` = glm(choice ~ treatment*condition, data = study1, family = binomial())),
                           estimate = "{estimate}{stars}",
                           gof_map = "nobs",
                           vcov = ~PROLIFIC_PID,
                           coef_map = list("treatmenttreatment" = "Treatment Decoy",
                                           "conditionrisk_seeking" = "Risk-seeking",
                                           "treatmenttreatment:conditionrisk_seeking" = "Decoy x Risk-seeking",
                                           "(Intercept)" = "Constant"),
                           title = "Likelihood of choosing focal lottery",
                           output='kableExtra') %>%
  kableExtra::add_footnote(label = c("\\textit{Note.} Parentheses show standard errors clustered at the participant level. \\newline",
                                     "$+$p < 0.10, *p < 0.05, **p < 0.01, ***p < 0.001"),
                           escape = F,
                           notation = "none",
                           threeparttable = T) %>%
  kableExtra::column_spec(1, width = "5cm")


# Separate risk-seeking and risk-averse condition 

modelsummary::modelsummary(list(`Risky Lottery` = glm(choice ~ treatment, data = study1[study1$condition == "risk_seeking", ], family = binomial()),
                                `Safe Lottery` = glm(choice ~ treatment, data = study1[study1$condition == "risk_averse", ], family = binomial())),
                           estimate = "{estimate}{stars}",
                           gof_map = "nobs",
                           vcov = ~PROLIFIC_PID,
                           coef_map = list("treatmenttreatment" = "Treatment Decoy",
                                           "conditionrisk_seeking" = "Risk-seeking",
                                           "treatmenttreatment:conditionrisk_seeking" = "Decoy x Risk-seeking",
                                           "(Intercept)" = "Constant"),
                           title = "Likelihood of choosing focal lottery",
                           output='kableExtra') %>%
  kableExtra::add_footnote(label = c("\\textit{Note.} Parentheses show standard errors clustered at the participant level. \\newline",
                                     "$+$p < 0.10, *p < 0.05, **p < 0.01, ***p < 0.001"),
                           escape = F,
                           notation = "none",
                           threeparttable = T) %>%
  kableExtra::column_spec(1, width = "5cm")

```


```{r}
# Separate risk-seeking and risk-averse condition
# Control for pair characteristic
# No specific lottery stands out

modelsummary::modelsummary(list(`Risky Lottery` = glm(choice ~ treatment + pair, data = study1[study1$condition == "risk_seeking", ], family = binomial()),
                                `Safe Lottery` = glm(choice ~ treatment + pair, data = study1[study1$condition == "risk_averse", ], family = binomial())),
                           estimate = "{estimate}{stars}",
                           gof_map = "nobs",
                           vcov = ~PROLIFIC_PID,
                           coef_map = list("treatmenttreatment" = "Treatment Decoy",
                                           "conditionrisk_seeking" = "Risk-seeking",
                                           "treatmenttreatment:conditionrisk_seeking" = "Decoy x Risk-seeking", "pair1" = "Pair 1", "pair2" = "Pair 2", "pair3" = "Pair 3", "pair4" = "Pair 4", "pair5" = "Pair 5",
                                           "(Intercept)" = "Constant"),
                           title = "Likelihood of choosing focal lottery",
                           output='kableExtra') %>%
  kableExtra::add_footnote(label = c("\\textit{Note.} Parentheses show standard errors clustered at the participant level. \\newline",
                                     "$+$p < 0.10, *p < 0.05, **p < 0.01, ***p < 0.001"),
                           escape = F,
                           notation = "none",
                           threeparttable = T) %>%
  kableExtra::column_spec(1, width = "5cm")
```


```{r}
# Separate risk-seeking and risk-averse condition
# Control for individual risk aversion
# No specific lottery stands out

modelsummary::modelsummary(list(`Risky Lottery` = glmer(choice ~ treatment + (1 | PROLIFIC_PID), data = study1[study1$condition == "risk_seeking", ], family = binomial()),
                                `Safe Lottery` = glmer(choice ~ treatment + (1 | PROLIFIC_PID), data = study1[study1$condition == "risk_averse", ], family = binomial())),
                           estimate = "{estimate}{stars}",
                           gof_map = "nobs",
                           coef_map = list("treatmenttreatment" = "Treatment Decoy",
                                           "conditionrisk_seeking" = "Risk-seeking",
                                           "treatmenttreatment:conditionrisk_seeking" = "Decoy x Risk-seeking", "pair1" = "Pair 1", "pair2" = "Pair 2", "pair3" = "Pair 3", "pair4" = "Pair 4", "pair5" = "Pair 5",
                                           "(Intercept)" = "Constant"),
                           title = "Likelihood of choosing focal lottery",
                           output='kableExtra') %>%
  kableExtra::add_footnote(label = c("\\textit{Note.} Parentheses show standard errors clustered at the participant level. \\newline",
                                     "$+$p < 0.10, *p < 0.05, **p < 0.01, ***p < 0.001"),
                           escape = F,
                           notation = "none",
                           threeparttable = T) %>%
  kableExtra::column_spec(1, width = "5cm")
```

```{r}
study1 %>%
  dplyr::mutate(condition = dplyr::recode_factor(condition,
                                                             'risk_averse' = 'Safe condition',
                                                             'risk_seeking' = 'Risky condition'),
                treatment = dplyr::recode_factor(treatment,
                                                             'control' = 'Control decoy',
                                                             'treatment' = 'Treatment decoy')) %>%
  dplyr::group_by(condition, treatment) %>%
  dplyr::summarize(mean = mean(choice),
                   n = dplyr::n(),
                   sd = sd(choice),
                   ci = qnorm(0.975) * sd/sqrt(n)) %>%
  ggplot2::ggplot(ggplot2::aes(x = condition,
                               y = mean,
                               fill = treatment)) +
  ggplot2::geom_col(position = 'dodge') +
  ggplot2::geom_text(ggplot2::aes(x = condition,
                                  y = 0.05,
                                  label = paste0(round(mean*100, 2), "%", "\n",
                                                 "n = ", n)),
                     color = 'white',
                     lineheight = 0.8,
                     position = ggplot2::position_dodge(1)) +
  ggplot2::coord_cartesian(ylim = c(0, 1),
                           expand = 0) +
  ggplot2::scale_fill_manual(values = c('#998ec3', '#f1a340')) +
  ggplot2::geom_errorbar(ggplot2::aes(ymin = mean - ci,
                                      ymax = mean + ci),
                         position = ggplot2::position_dodge(0.9),
                         width = 0.2) +
  papaja::theme_apa() +
  ggplot2::theme(legend.position = c(0.75, 0.9),
        legend.title = ggplot2::element_blank(),
        axis.title.x=ggplot2::element_blank(),
        axis.ticks.x=ggplot2::element_blank())+
  ggplot2::scale_y_continuous("Proportion Choosing Focal Lottery")
```

